### ISSUE TITLE
Plotting fails likely due to wide format of ggdata and tratios object

### ISSUE THREAD

**Issue by ropolomx** [richardsm32/source_attribution#3]
https://github.com/richardsm32/source_attribution/blob/8da47a5631a59ee4247af6bb90400ad90a6ca067/source_attribution.R#L72
Here `ggdata` and `tratios` are "wide" data frame. In `ggplot` it works better to work with "long" format (also known as tidy). 

In this case, you might only need `ggdata` (and not `tratios`), but needs to be reshaped. You might want to try the `pivot_longer` function from `tidyr`, which gets loaded with the `tidyverse` as well.

What you want would like similar to this:

| Subtype.ID|`unique(Subtype.ID)`|Source|sum_ratio|
|------------|----------------------|---------|----------|
|120|120|Chicken|1.0000000|

**Comment by ropolomx** [comment]
More information and examples of `pivot_longer`:
https://tidyr.tidyverse.org/reference/pivot_longer.html

**Comment by richardsm32** [comment]
I used pivot_longer and the data is now formatted correctly with 4 dependent values for each subtype.ID -> Each value holds the summed ratio for the respective source(s). Should be ready to create the graph.
